name: Deploy Vue.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | base64 --decode > private_key
        chmod 600 private_key
        mkdir -p ~/.ssh
        ssh-keyscan 185.216.25.179 >> ~/.ssh/known_hosts
        ssh -i private_key -o StrictHostKeyChecking=no mmi21h05@185.216.25.179 "exit"
        rsync -avz -e "ssh -i private_key" --delete dist/ mmi21h05@185.216.25.179:/home/mmi21h05/public_html/portfolio
        ssh -i private_key mmi21h05@185.216.25.179 << 'EOF'
          cd /home/mmi21h05/public_html/portfolio
          npm install --production
        EOF
      shell: bash
