name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print GITHUB_WORKSPACE
      run: echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: List project directory
      run: ls -la $GITHUB_WORKSPACE

    - name: Verify build output
      run: ls -la $GITHUB_WORKSPACE/dist

    - name: Check dist directory before deploy
      run: ls -la $GITHUB_WORKSPACE/dist

    - name: Create .ssh directory
      run: mkdir -p /home/runner/.ssh
      shell: bash

    - name: Add SSH key
      run: echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > /home/runner/.ssh/id_rsa
      shell: bash

    - name: Set permissions for SSH key
      run: chmod 600 /home/runner/.ssh/id_rsa
      shell: bash

    - name: Debug SSH connection
      run: |
        ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no mmi21h05@185.216.25.179 "echo 'SSH connection successful'"

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 185.216.25.179
        username: mmi21h05
        key: /home/runner/.ssh/id_rsa
        script: |
          rsync -avz $GITHUB_WORKSPACE/dist/ /home/mmi21h05/public_html/portfolio/
